### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by dries-c** [GameCraftPE/gamecraftpe.github.io#4]
add spanish cuz alot of players are spanish

**Comment by kevthebuzzard** [comment]
umm.. but I don't know how to use this could u help me please?

**Comment by Driesboy** [comment]
got ot the website and translate in the page all you see

Op 7-apr.-2017 20:37 schreef "kevthebuzzard" <notifications@github.com>:

**Comment by kevthebuzzard** [comment]
I am doing it right now!

**Comment by kevthebuzzard** [comment]
ALL THIS??

GAMECRAFT PE - SERVER NETWORK
JOIN US ON GAMECRAFTPE.

Custom minigames

We provide you the best game-experience with our home made custom minigames and great builds. Join us to experience the feeling and have countless hours of fun!

Great community

GameCraft PE has a friendly community with both new and experienced players. The community will help you out if you’re having troubles and the staff is always ready to help you out as well! The GameCraftPE community is filled with love. Join now and register at the forums!

Kind staff

Any issues? Other than the forums, why not just ask in-game? Our staff has lots of experience and can solve common issues.

VOTE FOR GAMECRAFT PE!
Vote for GameCraft PE and get some coins for every vote. You can buy awesome stuff with the coins, so be sure to vote on the link below. The monthly top voter also gets a free VIP 1 rank forever!

Vote here

VOTE
FULLY RESPONSIVE
The GameCraft Pe website is a clean and minimalistic one page website. GameCraft PE is fully responsive so it also fits perfect on iPads, tablets and smartphones.

 responsive mockup
We promise that you’ll like it, join us now!
GAMECRAFT PE
TAKE A LOOK ON OUR WEBSHOP FOR EXTRA FEATURES
SOME OF THE EXTRA FEATURES WE OFFER

visit buycraft
Do you want to show some love for our hard work? You can do that by donating to the server. In return we give you great ranks, extra permissions or ingame items. How cool is that?

Visit our buycraft to see the perks, items and features you get when you donate and also their prices. We would really appriciate that.

COMING SOON
50
players online average
48160
players joined in total
2,5
years online
20
great staff members
THE TEAM BEHIND GAMECRAFT PE
notch
DRIESBOY

He is the founder and current owner of GameCraft PE with SeppeLK. He also builds and develops all plugins.

steve
SEPPELK

This is SeppeLK. He is the second owner of GameCraft PE beside Driesboy. He is Admin on the server and owns the youtube channel. He is also known as TheBluePinguin on minecraft pc.

enderman
THE STAFF

We've got at least one staff member for ech minigame on our server. If you have any issues or questions you can always count on them!

Do you like what you see? Join GameCraft PE, it’s free!
GAMECRAFTPE.TK
OUR MINIGAMES, WE'RE SURE YOU'LL LOVE THEM!
Factions
KITS

Our skywars server has kits. Kits are extra abilities you get when your game starts. You can select a kit before the game starts. You can buy kits with ingame coins or you can buy coins in the gamecraft shop. (see link to shop)

Prison
SKYWARS

Skywars is a popular Minecraft minigame with a simple premise: fight until one player (or team) is left alive. The catch is that you begin on a small island. It's up to you to build bridges to attack other players, or walls to defend yourself.

KitPvP
MAPS

In skywars you have multiple maps to play in. Every map has it's own title and map specific islands. You have for example the map candy which contains islands with candy on it. We created a large variation so you can choose what you like to play.

GAMECRAFTPE.TK
GAMECRAFT PE SERVER NETWORK
Website made by Seppe Van Schelstraete and Dries Coenen

**Comment by dries-c** [comment]
yes but edit in in the code

**Comment by kevthebuzzard** [comment]
where!? i don' t get that part

**Comment by kevthebuzzard** [comment]
I already have the first paragraph

**Comment by dries-c** [comment]
wait check your mail
i will invite you

**Comment by kevthebuzzard** [comment]
okei

**Comment by dries-c** [comment]
so you can start

**Comment by kevthebuzzard** [comment]
yeah i got what u sent me

**Comment by dries-c** [comment]
https://github.com/GameCraftPE/gamecraftpe.github.io/tree/Spanish

**Comment by kevthebuzzard** [comment]
click that?

**Comment by dries-c** [comment]
accept and then you can edit our code

**Comment by dries-c** [comment]
yes

**Comment by dries-c** [comment]
i need to go bye

**Comment by kevthebuzzard** [comment]
https://gyazo.com/9a29e93596b5d3d4de3c3dfb65ca6b2d

**Comment by kevthebuzzard** [comment]
which link

**Comment by kevthebuzzard** [comment]
ok byee!

**Comment by kevthebuzzard** [comment]
What do u think!? Is it good?

**Comment by dries-c** [comment]
i dont see things

**Comment by kevthebuzzard** [comment]
I am doing it again

**Comment by kevthebuzzard** [comment]
Are u able to see it now??
